import = ["~/.config/alacritty/base16-tomorrow-night.toml"]

[shell]
program = '/opt/homebrew/bin/bash'
args = ["--login"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 16

[cursor]
[cursor.style]
blinking = "Never"

[cursor.vi_mode_style]
shape = "Beam"
blinking = "Never"

[scrolling]
history = 100000
multiplier = 3
